# Référence DonnÉlite — Schema Registry (documentation)
# En local, Bitnami applique SCHEMA_REGISTRY_AVRO_COMPATIBILY_LEVEL via docker-compose.

listeners=http://0.0.0.0:8081
kafkastore.bootstrap.servers=kafka:9092
host.name=schema-registry
schema.compatibility.level=BACKWARD
kafkastore.topic=_schemas
kafkastore.topic.replication.factor=1
